export const regExp = {
  email: /\S+@\S+\.\S+/,
  domainEmail: /^@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  professionalEmail: /[a-z0-9@.,]+/,
  customUrl: /^[a-zA-Z0-9-]+$/,
  onlyNumbers: /^\d+$/,
  onlyAlphabet: /^[A-Za-z\s]+$/,
  onlyAlphabetWithSpaces: /^(?=.*[A-Za-z])[A-Za-z\s]*$/,
  phoneRegExp:
    /^((\+[1-9]{1,4}[ -]?)|(\([0-9]{2,3}\)[ -]?)|([0-9]{2,4})[ -]?)*?[0-9]{3,4}[ -]?[0-9]{3,4}$/,
  phoneNoRegExp: /^[0-9]{10}$/,
  indianPhoneNoRegExp: /^(?:\+91|91)?[789]\d{9}$/,
  minChar10Required: /^[a-zA-Z0-9 ]{10,}$/,
  alphabetOnlywithNoSpaceStartMin15: /^[a-zA-Z]{15,}$/,
  strLowerCase: /^(?=.*[a-z])/,
  strUpperCase: /^(?=.*[A-Z])/,
  containsNum: /^(?=.*[0-9])/,
  containsSpecialChar: /^(?=.*[!@#$%^&*])/,
  pinCode: /^\d{6}$/,
  decimalNum: /^\d*(\.\d{0,})?$/,
  point: /^\d*\.$/,
  numberWithSpecialChar: /^[0-9!@#$%^&*]+$/,
  onlyAlphabetNumber: /^[a-zA-Z0-9 ]+$/,
  otp6Digit: /^\d{6}$/,
  numberOnly3To12: /^(3|[4-9]|1[0-2])$/,
  numberOnly4To12: /^(4|[5-9]|1[0-2])$/,
  onlyCapsAlphabetNumber: /^[A-Z0-9]*$/,
  numberOnly1To12: /^(1[0-2]|[1-9])$/,
  noOnlyNumbers: /^(?!^\d+$).+/,
  validUrl:
    /^https:\/\/(www\.)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/i,
  standardEmail: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/i,
  minWord20Required: /^(?:\b\w+\b[\s]*){1,}$/
};
